#!/bin/bash
# Copyright (c) 2021 Matus Chochlik
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt

cp -u ctcache/clang-tidy /usr/local/bin/clang-tidy-16
cp -u ctcache/clang-tidy-cache /usr/local/bin/
